/********************************************************************
* gtrackDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error gtrackDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablegtrackDict();
extern void G__cpp_setup_inheritancegtrackDict();
extern void G__cpp_setup_typetablegtrackDict();
extern void G__cpp_setup_memvargtrackDict();
extern void G__cpp_setup_globalgtrackDict();
extern void G__cpp_setup_memfuncgtrackDict();
extern void G__cpp_setup_funcgtrackDict();
extern void G__set_cpp_environmentgtrackDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GTrack.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__gtrackDictLN_TClass;
extern G__linked_taginfo G__gtrackDictLN_TBuffer;
extern G__linked_taginfo G__gtrackDictLN_TMemberInspector;
extern G__linked_taginfo G__gtrackDictLN_TObject;
extern G__linked_taginfo G__gtrackDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__gtrackDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__gtrackDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__gtrackDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__gtrackDictLN_lesslEintgR;
extern G__linked_taginfo G__gtrackDictLN_GInfo;
extern G__linked_taginfo G__gtrackDictLN_GInfocLcLGSensor;
extern G__linked_taginfo G__gtrackDictLN_GInfocLcLGSlice;
extern G__linked_taginfo G__gtrackDictLN_allocatorlEpairlEconstsPintcOdoublegRsPgR;
extern G__linked_taginfo G__gtrackDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__gtrackDictLN_pairlEintcOdoublegR;
extern G__linked_taginfo G__gtrackDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__gtrackDictLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__gtrackDictLN_pairlEmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcLcLiteratorcOboolgR;
extern G__linked_taginfo G__gtrackDictLN_vectorlEGInfocLcLGSensorcOallocatorlEGInfocLcLGSensorgRsPgR;
extern G__linked_taginfo G__gtrackDictLN_vectorlEGInfocLcLGSensorcOallocatorlEGInfocLcLGSensorgRsPgRcLcLiterator;
extern G__linked_taginfo G__gtrackDictLN_reverse_iteratorlEvectorlEGInfocLcLGSensorcOallocatorlEGInfocLcLGSensorgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__gtrackDictLN_GInfocLcLGPeak;
extern G__linked_taginfo G__gtrackDictLN_vectorlEGInfocLcLGSlicecOallocatorlEGInfocLcLGSlicegRsPgR;
extern G__linked_taginfo G__gtrackDictLN_vectorlEGInfocLcLGSlicecOallocatorlEGInfocLcLGSlicegRsPgRcLcLiterator;
extern G__linked_taginfo G__gtrackDictLN_reverse_iteratorlEvectorlEGInfocLcLGSlicecOallocatorlEGInfocLcLGSlicegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__gtrackDictLN_GInfocLcLGTrack;
extern G__linked_taginfo G__gtrackDictLN_vectorlEmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOallocatorlEmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__gtrackDictLN_vectorlEmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOallocatorlEmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__gtrackDictLN_reverse_iteratorlEvectorlEmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOallocatorlEmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef map<int,double,less<int>,allocator<pair<const int,double> > > G__maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR;
typedef vector<GInfo::GSensor,allocator<GInfo::GSensor> > G__vectorlEGInfocLcLGSensorcOallocatorlEGInfocLcLGSensorgRsPgR;
typedef vector<GInfo::GSlice,allocator<GInfo::GSlice> > G__vectorlEGInfocLcLGSlicecOallocatorlEGInfocLcLGSlicegRsPgR;
typedef vector<map<int,double,less<int>,allocator<pair<const int,double> > >,allocator<map<int,double,less<int>,allocator<pair<const int,double> > > > > G__vectorlEmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOallocatorlEmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgR;
